name: Release CSGHub

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 30

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"


      - name: Package Custom Artifact
        id: package_artifact
        run: |
          docker_artifact="csghub-docker-compose-${{ github.ref_name }}.tgz"
          chart_artifact="csghub-helm-chart-${{ github.ref_name }}.tgz"
          tar -zcf $docker_artifact docker-compose/csghub
          tar -zcf $chart_artifact docker-compose/csghub
          artifacts="$docker_artifact,$chart_artifact"
          echo "artifacts=$artifacts" >> $GITHUB_OUTPUT

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.package_artifact.outputs.artifacts }}
          
